---
name: Check

on:
  push:
    branches:
      - "doc-snippet-bot-2"

jobs:
  typecheck:
    name: Typecheck (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - run: cd ./doc-snippet-bot && npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SEAMAPI_NPM_TOKEN }}
      # - run: npm run build
      - name: Check types
        run: npm run typecheck
